[project]
name = "users-microservice"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "fastapi[all]>=0.115.12",
    "ruff>=0.11.2",
]

[tool.ruff]
line-length = 100
